{
  "openapi": "3.1.0",
  "info": {
    "title": "Attio Standard Objects",
    "version": "2.0.0"
  },
  "security": [
    {
      "oauth2": []
    }
  ],
  "servers": [
    {
      "url": "https://api.attio.com",
      "description": "Production"
    }
  ],
  "components": {
    "securitySchemes": {
      "oauth2": {
        "type": "oauth2",
        "description": "This API uses OAuth 2.0 with the authorization code grant flow.",
        "flows": {
          "authorizationCode": {
            "authorizationUrl": "https://app.attio.com/authorize",
            "tokenUrl": "https://app.attio.com/oauth/token",
            "scopes": {
              "user_management:read": "View workspace members.",
              "user_management:read-write": "View workspace members.",
              "record_permission:read": "View, and optionally write, records.",
              "record_permission:read-write": "View, and optionally write, records.",
              "object_configuration:read": "View, and optionally write, the configuration and attributes of objects.",
              "object_configuration:read-write": "View, and optionally write, the configuration and attributes of objects.",
              "list_entry:read": "View, and optionally write, the entries in a list.",
              "list_entry:read-write": "View, and optionally write, the entries in a list.",
              "list_configuration:read": "View, and optionally write, the configuration and attributes of lists.",
              "list_configuration:read-write": "View, and optionally write, the configuration and attributes of lists.",
              "public_collection:read": "View, and optionally write, both the settings and information within public collections.",
              "public_collection:read-write": "View, and optionally write, both the settings and information within public collections.",
              "private_collection:read": "View, and optionally modify, both the settings and information of all collections within the workspace, regardless of their access settings.",
              "private_collection:read-write": "View, and optionally modify, both the settings and information of all collections within the workspace, regardless of their access settings.",
              "comment:read": "View comments (and threads), and optionally write comments.",
              "comment:read-write": "View comments (and threads), and optionally write comments.",
              "task:read": "View, and optionally write, tasks.",
              "task:read-write": "View, and optionally write, tasks.",
              "note:read": "View, and optionally write, notes.",
              "note:read-write": "View, and optionally write, notes.",
              "webhook:read": "View, and optionally manage, webhooks.",
              "webhook:read-write": "View, and optionally manage, webhooks."
            }
          }
        }
      }
    }
  },
  "paths": {
    "/v2/objects/people/records/query": {
      "post": {
        "summary": "List person records ",
        "description": "Lists person records, with the option to filter and sort results.\n\nRequired scopes: `record_permission:read`, `object_configuration:read`.",
        "tags": [
          "People"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read",
              "object_configuration:read"
            ]
          }
        ]
      }
    },
    "/v2/objects/people/records": {
      "post": {
        "summary": "Create a person Record",
        "description": "Creates a new person Record. This endpoint will throw on conflicts of unique attributes, like `email_addresses`. If you would prefer to update person records on conflicts, please use the Assert person record endpoint instead. Please note, the `avatar_url` attribute cannot currently be set via the API.\n\nRequired scopes: `record_permission:read-write`, `object_configuration:read`.",
        "tags": [
          "People"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read-write",
              "object_configuration:read"
            ]
          }
        ]
      },
      "put": {
        "summary": "Assert a person Record",
        "description": "Use this endpoint to create or update person records, using a unique attribute to search for existing People (for example the `email_addresses` attribute). If a person is found with the same value for the matching attribute, that person will be updated. If no person with the same value for the matching attribute is found, a new person will be created instead. If you would like to avoid matching, please use the Create person endpoint.\n\n\nIf the matching attribute is a mu[...]",
        "tags": [
          "People"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read-write",
              "object_configuration:read"
            ]
          }
        ]
      }
    },
    "/v2/objects/people/records/{record_id}": {
      "get": {
        "summary": "Get a person Record",
        "description": "Gets a single person record by its `record_id`.\n\nRequired scopes: `record_permission:read`, `object_configuration:read`.",
        "tags": [
          "People"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read",
              "object_configuration:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update a person Record",
        "description": "Use this endpoint to update person records by `record_id`. If the update payload includes multiselect attributes, the values supplied will be created and prepended to the list of values that already exist (if any). Use the [Assert person endpoint](/reference/put_v2-objects-people-records) to overwrite or remove multiselect attribute values. Please note, the `avatar_url` attribute cannot currently be updated via the API.\n\nRequired scopes: `record_permission:read-write`, [...]",
        "tags": [
          "People"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read-write",
              "object_configuration:read"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete a person Record",
        "description": "Deletes a single person record by ID.\n\nRequired scopes: `object_configuration:read`, `record_permission:read-write`.",
        "tags": [
          "People"
        ],
        "security": [
          {
            "oauth2": [
              "object_configuration:read",
              "record_permission:read-write"
            ]
          }
        ]
      }
    },
    "/v2/objects/people/records/{record_id}/attributes/{attribute}/values": {
      "get": {
        "summary": "List person record attribute values",
        "description": "Gets all values for a given attribute on a person Record. If the attribute is historic, this endpoint has the ability to return all historic values using the `show_historic` query param.\n\nRequired scopes: `record_permission:read`, `object_configuration:read`.",
        "tags": [
          "People"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read",
              "object_configuration:read"
            ]
          }
        ]
      }
    },
    "/v2/objects/people/records/{record_id}/entries": {
      "get": {
        "summary": "List person record entries",
        "description": "List all entries, across all lists, for which this person record is the parent.\n\nRequired scopes: `record_permission:read`, `object_configuration:read`, `list_entry:read`.",
        "tags": [
          "People"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read",
              "object_configuration:read",
              "list_entry:read"
            ]
          }
        ]
      }
    },
    "/v2/objects/companies/records/query": {
      "post": {
        "summary": "List company records",
        "description": "Lists company records, with the option to filter and sort results.\n\nRequired scopes: `record_permission:read`, `object_configuration:read`.",
        "tags": [
          "Companies"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read",
              "object_configuration:read"
            ]
          }
        ]
      }
    },
    "/v2/objects/companies/records": {
      "post": {
        "summary": "Create a company record",
        "description": "Creates a new company record. This endpoint will throw on conflicts of unique attributes, like `domains`. If you would prefer to update company records on conflicts, please use the Assert company record endpoint instead. Please note, the `logo_url` attribute cannot currently be set via the API.\n\nRequired scopes: `record_permission:read-write`, `object_configuration:read`.",
        "tags": [
          "Companies"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read-write",
              "object_configuration:read"
            ]
          }
        ]
      },
      "put": {
        "summary": "Assert a company record",
        "description": "Use this endpoint to create or update company records, using a unique attribute to search for existing companies (for example, the `domains` attribute). If a company is found with the same value for the matching attribute, that company will be updated. If no company with the same value for the matching attribute is found, a new company will be created instead. If you would like to avoid matching, please use the Create company endpoint.\n\n\nIf the matching attribute is a [...]",
        "tags": [
          "Companies"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read-write",
              "object_configuration:read"
            ]
          }
        ]
      }
    },
    "/v2/objects/companies/records/{record_id}": {
      "get": {
        "summary": "Get a company record",
        "description": "Gets a single company record by its `record_id`.\n\nRequired scopes: `record_permission:read`, `object_configuration:read`.",
        "tags": [
          "Companies"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read",
              "object_configuration:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update a company record",
        "description": "Use this endpoint to update company records by `record_id`. If the update payload includes multiselect attributes, the values supplied will be created and prepended to the list of values that already exist (if any). Use the [Assert company endpoint](/reference/put_v2-objects-companies-records) to overwrite or remove multiselect attribute values. Please note, the `logo_url` attribute cannot currently be updated via the API.\n\nRequired scopes: `record_permission:read-write[...]",
        "tags": [
          "Companies"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read-write",
              "object_configuration:read"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete a company record",
        "description": "Deletes a single company record by ID.\n\nRequired scopes: `object_configuration:read`, `record_permission:read-write`.",
        "tags": [
          "Companies"
        ],
        "security": [
          {
            "oauth2": [
              "object_configuration:read",
              "record_permission:read-write"
            ]
          }
        ]
      }
    },
    "/v2/objects/companies/records/{record_id}/attributes/{attribute}/values": {
      "get": {
        "summary": "List company record attribute values",
        "description": "Gets all values for a given attribute on a company record. If the attribute is historic, this endpoint has the ability to return all historic values using the `show_historic` query param.\n\nRequired scopes: `record_permission:read`, `object_configuration:read`.",
        "tags": [
          "Companies"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read",
              "object_configuration:read"
            ]
          }
        ]
      }
    },
    "/v2/objects/companies/records/{record_id}/entries": {
      "get": {
        "summary": "List company record entries",
        "description": "List all entries, across all lists, for which this company record is the parent.\n\nRequired scopes: `record_permission:read`, `object_configuration:read`, `list_entry:read`.",
        "tags": [
          "Companies"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read",
              "object_configuration:read",
              "list_entry:read"
            ]
          }
        ]
      }
    },
    "/v2/objects/users/records/query": {
      "post": {
        "summary": "List user records",
        "description": "Lists user records, with the option to filter and sort results.\n\nRequired scopes: `record_permission:read`, `object_configuration:read`.",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read",
              "object_configuration:read"
            ]
          }
        ]
      }
    },
    "/v2/objects/users/records": {
      "post": {
        "summary": "Create a user record",
        "description": "Creates a new user record. This endpoint will throw on conflicts of unique attributes, like `primary_email_address`. If you would prefer to update user records on conflicts, please use the Assert user record endpoint instead. Please note, the `avatar_url` attribute cannot currently be set via the API.\n\nRequired scopes: `record_permission:read-write`, `object_configuration:read`.",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read-write",
              "object_configuration:read"
            ]
          }
        ]
      },
      "put": {
        "summary": "Assert a user record",
        "description": "Use this endpoint to create or update user records, using a unique attribute to search for existing users (for example the `primary_email_address` attribute). If a user is found with the same value for the matching attribute, that user will be updated, otherwise a new user will be created instead. If the matching attribute is a multiselect attribute, new values will be added and existing values will not be deleted. For any other multiselect attribute, all values will be e[...]",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read-write",
              "object_configuration:read"
            ]
          }
        ]
      }
    },
    "/v2/objects/users/records/{record_id}": {
      "get": {
        "summary": "Get a user record",
        "description": "Gets a single user record by its `record_id`.\n\nRequired scopes: `record_permission:read`, `object_configuration:read`.",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read",
              "object_configuration:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update a user Record",
        "description": "Use this endpoint to update user records by `record_id`. If the update payload includes multiselect attributes, the values supplied will be created and prepended to the list of values that already exist (if any). Use the [Assert user endpoint](/reference/put_v2-objects-users-records) to overwrite or remove multiselect attribute values. Please note, the `avatar_url` attribute cannot currently be updated via the API.\n\nRequired scopes: `record_permission:read-write`, `obje[...]",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read-write",
              "object_configuration:read"
            ]
          }
        ]
      },
      "delete": {
        "summary": "Delete a user record",
        "description": "Deletes a single user record by ID.\n\nRequired scopes: `object_configuration:read`, `record_permission:read-write`.",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "oauth2": [
              "object_configuration:read",
              "record_permission:read-write"
            ]
          }
        ]
      }
    },
    "/v2/objects/users/records/{record_id}/attributes/{attribute}/values": {
      "get": {
        "summary": "List user record attribute values",
        "description": "Gets all values for a given attribute on a user record. If the attribute is historic, this endpoint has the ability to return all historic values using the `show_historic` query param.\n\nRequired scopes: `record_permission:read`, `object_configuration:read`.",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read",
              "object_configuration:read"
            ]
          }
        ]
      }
    },
    "/v2/objects/users/records/{record_id}/entries": {
      "get": {
        "summary": "List user record entries",
        "description": "List all entries, across all lists, for which this user record is the parent.\n\nRequired scopes: `record_permission:read`, `object_configuration:read`, `list_entry:read`.",
        "tags": [
          "Users"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read",
              "object_configuration:read",
              "list_entry:read"
            ]
          }
        ]
      }
    },
    "/v2/objects/deals/records": {
      "put": {
        "summary": "Assert a deal record",
        "description": "Use this endpoint to create or update deal records, using a unique attribute to search for existing deals. By default, deals do not have a unique attribute, so you should add your own attribute with a unique constraint to use this API. If a deal is found with the same value for the matching attribute, that deal will be updated, otherwise a new deal will be created instead. If the matching attribute is a multiselect attribute, new values will be added and existing values w[...]",
        "tags": [
          "Deals"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read-write",
              "object_configuration:read"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create a deal record",
        "description": "Creates a new deal record. This endpoint will throw on conflicts of unique attributes, if defined. If you would prefer to update deal records on conflicts, please use the Assert deal record endpoint instead.\n\nRequired scopes: `record_permission:read-write`, `object_configuration:read`.",
        "tags": [
          "Deals"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read-write",
              "object_configuration:read"
            ]
          }
        ]
      }
    },
    "/v2/objects/deals/records/{record_id}": {
      "delete": {
        "summary": "Delete a deal record",
        "description": "Deletes a single deal record by ID.\n\nRequired scopes: `object_configuration:read`, `record_permission:read-write`.",
        "tags": [
          "Deals"
        ],
        "security": [
          {
            "oauth2": [
              "object_configuration:read",
              "record_permission:read-write"
            ]
          }
        ]
      },
      "get": {
        "summary": "Get a deal record",
        "description": "Gets a single deal record by its `record_id`.\n\nRequired scopes: `record_permission:read`, `object_configuration:read`.",
        "tags": [
          "Deals"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read",
              "object_configuration:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update a deal record",
        "description": "Use this endpoint to update deal records by `record_id`. If the update payload includes multiselect attributes, the values supplied will be created and prepended to the list of values that already exist (if any). Use the [Assert deal endpoint](/reference/put_v2-objects-deals-records) to overwrite or remove multiselect attribute values.\n\nRequired scopes: `record_permission:read-write`, `object_configuration:read`.",
        "tags": [
          "Deals"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read-write",
              "object_configuration:read"
            ]
          }
        ]
      }
    },
    "/v2/objects/deals/records/{record_id}/attributes/{attribute}/values": {
      "get": {
        "summary": "List deal record attribute values",
        "description": "Gets all values for a given attribute on a deal record. If the attribute is historic, this endpoint has the ability to return all historic values using the `show_historic` query param.\n\nRequired scopes: `record_permission:read`, `object_configuration:read`.",
        "tags": [
          "Deals"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read",
              "object_configuration:read"
            ]
          }
        ]
      }
    },
    "/v2/objects/deals/records/{record_id}/entries": {
      "get": {
        "summary": "List deal record entries",
        "description": "List all entries, across all lists, for which this deal record is the parent.\n\nRequired scopes: `record_permission:read`, `object_configuration:read`, `list_entry:read`.",
        "tags": [
          "Deals"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read",
              "object_configuration:read",
              "list_entry:read"
            ]
          }
        ]
      }
    },
    "/v2/objects/deals/records/query": {
      "post": {
        "summary": "List deal records",
        "description": "Lists deal records, with the option to filter and sort results.\n\nRequired scopes: `record_permission:read`, `object_configuration:read`.",
        "tags": [
          "Deals"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read",
              "object_configuration:read"
            ]
          }
        ]
      }
    },
    "/v2/objects/workspaces/records": {
      "put": {
        "summary": "Assert a workspace record",
        "description": "Use this endpoint to create or update workspace records, using a unique attribute to search for existing workspaces (for example the `workspace_id` attribute). If a workspace is found with the same value for the matching attribute, that workspace will be updated, otherwise a new workspace will be created instead. If the matching attribute is a multiselect attribute, new values will be added and existing values will not be deleted. For any other multiselect attribute, all [...]",
        "tags": [
          "Workspaces"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read-write",
              "object_configuration:read"
            ]
          }
        ]
      },
      "post": {
        "summary": "Create a workspace record",
        "description": "Creates a new workspace record. This endpoint will throw on conflicts of unique attributes, like `workspace_id`. If you would prefer to update workspace records on conflicts, please use the Assert workspace record endpoint instead.\n\nRequired scopes: `record_permission:read-write`, `object_configuration:read`.",
        "tags": [
          "Workspaces"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read-write",
              "object_configuration:read"
            ]
          }
        ]
      }
    },
    "/v2/objects/workspaces/records/{record_id}": {
      "delete": {
        "summary": "Delete a workspace record",
        "description": "Deletes a single workspace record by ID.\n\nRequired scopes: `object_configuration:read`, `record_permission:read-write`.",
        "tags": [
          "Workspaces"
        ],
        "security": [
          {
            "oauth2": [
              "object_configuration:read",
              "record_permission:read-write"
            ]
          }
        ]
      },
      "get": {
        "summary": "Get a workspace record",
        "description": "Gets a single workspace record by its `record_id`.\n\nRequired scopes: `record_permission:read`, `object_configuration:read`.",
        "tags": [
          "Workspaces"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read",
              "object_configuration:read"
            ]
          }
        ]
      },
      "patch": {
        "summary": "Update a workspace Record",
        "description": "Use this endpoint to update workspace records by `record_id`. If the update payload includes multiselect attributes, the values supplied will be created and prepended to the list of values that already exist (if any). Use the [Assert workspace endpoint](/reference/put_v2-objects-workspaces-records) to overwrite or remove multiselect attribute values.\n\nRequired scopes: `record_permission:read-write`, `object_configuration:read`.",
        "tags": [
          "Workspaces"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read-write",
              "object_configuration:read"
            ]
          }
        ]
      }
    },
    "/v2/objects/workspaces/records/{record_id}/attributes/{attribute}/values": {
      "get": {
        "summary": "List workspace record attribute values",
        "description": "Gets all values for a given attribute on a workspace record. If the attribute is historic, this endpoint has the ability to return all historic values using the `show_historic` query param.\n\nRequired scopes: `record_permission:read`, `object_configuration:read`.",
        "tags": [
          "Workspaces"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read",
              "object_configuration:read"
            ]
          }
        ]
      }
    },
    "/v2/objects/workspaces/records/{record_id}/entries": {
      "get": {
        "summary": "List workspace record entries",
        "description": "List all entries, across all lists, for which this workspace record is the parent.\n\nRequired scopes: `record_permission:read`, `object_configuration:read`, `list_entry:read`.",
        "tags": [
          "Workspaces"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read",
              "object_configuration:read",
              "list_entry:read"
            ]
          }
        ]
      }
    },
    "/v2/objects/workspaces/records/query": {
      "post": {
        "summary": "List workspace records",
        "description": "Lists workspace records, with the option to filter and sort results.\n\nRequired scopes: `record_permission:read`, `object_configuration:read`.",
        "tags": [
          "Workspaces"
        ],
        "security": [
          {
            "oauth2": [
              "record_permission:read",
              "object_configuration:read"
            ]
          }
        ]
      }
    }
  },
  "webhooks": {}
}